server {
    listen 80;
    server_name ynotes.ru;

    return 301 https://ynotes.ru$request_uri;
}

server {
    listen 443 ssl;
    server_name ynotes.ru;

    ssl_certificate /etc/nginx/certs/fullchain.pem;
    ssl_certificate_key /etc/nginx/certs/privkey.pem;
    root /usr/share/nginx/html;
    index index.html;
    # backend
    location /api/ {
        proxy_pass http://backend:8080;
    }
    # frontend
    location / {
        try_files $uri $uri/ /index.html;
    }
}